import type { ReactNode } from "react";

type Span = 12 | 8 | 6 | 4 | 3;
type RowSpan = 1 | 2;

// Pentagram case-study model: 12-col grid with cell weight driven by span, not
// tile uniformity. Rule: one feature per row spanning ≥6, smaller siblings
// spanning 3–4 beside; alternate visual weight by group so the page reads as
// edited rather than autogenerated.
const colSpanClass: Record<Span, string> = {
  12: "col-span-12",
  8: "col-span-12 md:col-span-8",
  6: "col-span-12 md:col-span-6",
  4: "col-span-12 md:col-span-4",
  3: "col-span-12 sm:col-span-6 md:col-span-3",
};

const rowSpanClass: Record<RowSpan, string> = {
  1: "",
  2: "md:row-span-2",
};

type ScaleGridProps = {
  children: ReactNode;
  className?: string;
};

function ScaleGridRoot({ children, className }: ScaleGridProps) {
  const base = "grid grid-cols-12 gap-x-6 gap-y-12";
  const merged = `${base} ${className ?? ""}`.trim();
  return <div className={merged}>{children}</div>;
}

type ScaleGridCellProps = {
  children: ReactNode;
  span: Span;
  rowSpan?: RowSpan;
  className?: string;
};

function ScaleGridCell({ children, span, rowSpan = 1, className }: ScaleGridCellProps) {
  const merged = `${colSpanClass[span]} ${rowSpanClass[rowSpan]} ${className ?? ""}`.trim();
  return <div className={merged}>{children}</div>;
}

export const ScaleGrid = Object.assign(ScaleGridRoot, {
  Cell: ScaleGridCell,
});
